const PUT_CERTIFICATES = "PUT_CERTIFICATES";
const PUT_PAGES_COUNT = "PUT_PAGES_COUNT";
const TRIGGER_CERTIFICATE_UPDATE = "TRIGGER_CERTIFICATE_UPDATE";
export default {
    PUT_CERTIFICATES,
    PUT_PAGES_COUNT,
    TRIGGER_CERTIFICATE_UPDATE
}