const PUT_TOKEN = "PUT_TOKEN";
const DELETE_TOKEN = "DELETE_TOKEN";
const SHOW_ALERT = "SHOW_ALERT";
const HIDE_ALERT = "HIDE_ALERT";
const PUT_ALERT_MESSAGE = "PUT_ALERT_MESSAGE";
const DELETE_ALERT_MESSAGE = "DELETE_ALERT_MESSAGE";

export default {
    PUT_TOKEN,
    DELETE_TOKEN,
    SHOW_ALERT,
    HIDE_ALERT,
    PUT_ALERT_MESSAGE,
    DELETE_ALERT_MESSAGE
}